/* insert into location */
insert into location(id,region_code,district_code) values(1, 'NE','01')
insert into location(id,region_code,district_code) values(2, 'NE','02')
insert into location(id,region_code,district_code) values(3, 'NE','03')
insert into location(id,region_code,district_code) values(4, 'NE','04')
insert into location(id,region_code,district_code) values(5, 'GU','01')
insert into location(id,region_code,district_code) values(6, 'GU','02')
insert into location(id,region_code,district_code) values(7, 'GU','03')
insert into location(id,region_code,district_code) values(8, 'GU','04')
insert into location(id,region_code,district_code) values(9, 'MW','01')
insert into location(id,region_code,district_code) values(10, 'MW','02')
insert into location(id,region_code,district_code) values(11, 'MW','03')
insert into location(id,region_code,district_code) values(12, 'MW','04')

/* insert into delear */
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (1   ,'10102', 'UNIVERSITY MAZDA'			, 'A', 1	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (2   ,'10131', 'OAK TREE MAZDA'			, 'A', 2	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (3   ,'10707', 'TUSTIN MAZDA'				, 'A', 3	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (4   ,'34439', 'WANTAGH MAZDA'			, 'A', 4	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (5   ,'34521', 'MAZDA OF NORTH MIAMI'		, 'A', 5	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (6   ,'34541', 'MAZDA SOUTH'				, 'A', 6	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (7   ,'50210', 'OCEAN MAZDA'				, 'A', 7	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (8   ,'51617', 'CULVER CITY MAZDA'		, 'A', 8	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (9   ,'61566', 'GALPIN MAZDA'				, 'A', 9	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (10  ,'10803', 'CLASSIC MAZDA'			, 'A', 10	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (11  ,'10823', 'CAPITOL MAZDA'			, 'A', 11	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (12  ,'34575', 'CARDINALEWAY MAZDA VEGAS'	, 'A', 12	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (13  ,'61534', 'SPORT MAZDA'				, 'A', 1	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (14  ,'61593', 'MAZDA OF DELRAY BEACH'	, 'A', 2	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (15  ,'61622', 'WAYNE MAZDA'				, 'A', 3	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (16  ,'61623', 'GUNTHER MAZDA'			, 'A', 4	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (17  ,'61624', 'MAZDA OF LODI'			, 'A', 5	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (18  ,'60135', 'CORY FAIRBANKS MAZDA'		, 'A', 6	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (19  ,'61420', 'JEFF HAAS MAZDA'			, 'A', 7	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (20  ,'61429', 'BOB BAKER MAZDA'			, 'A', 8	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (21  ,'61449', 'MAZDA OF SOUTH CHARLOTTE'	, 'A', 9	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (22  ,'61540', 'MAZDA OF EVERETT'			, 'A', 10	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (23  ,'61590', 'QUIRK MAZDA'				, 'A', 11	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (24  ,'61610', 'WALSER BURNSVILLE MAZDA'	, 'A', 12	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (25  ,'61614', 'NORTH PARK MAZDA'			, 'A', 1	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (26  ,'61635', 'LUTHER BROOKDALE MAZDA'	, 'A', 2	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (27  ,'60181', 'DUBLIN MAZDA'				, 'A', 3	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (28  ,'61471', 'ROGER MAZDA GEORGETOWN'	, 'A', 4	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (29  ,'61611', 'HAMILTON MAZDA'			, 'A', 5	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (30  ,'61613', 'NORTH PENN MAZDA'			, 'A', 6	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (31  ,'61626', 'MORRIES MINNETONKA MAZDA'	, 'A', 7	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (32  ,'61629', 'MAZDA OF WEST CHESTER'	, 'A', 8	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (33  ,'61637', 'PUTNAM MAZDA'				, 'A', 9	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (34  ,'60170', 'SMITH HAVEN MAZDA'		, 'A', 10	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (35  ,'60172', 'RILEY MAZDA'				, 'A', 11	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (36  ,'60188', 'PALISADES MAZDA'			, 'A', 12	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (37  ,'61432', 'CLASSIC MAZDA'			, 'A', 1	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (38  ,'61504', 'WERNER MAZDA'				, 'A', 2	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (39  ,'61542', 'MAZDA OF WEST RIDGE'		, 'A', 3	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (40  ,'61561', 'MORRIES INVER GROVE MAZDA', 'A', 4	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (41  ,'61628', 'COLONIAL MAZDA'			, 'A', 5	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (42  ,'34638', 'PUGI MAZDA'				, 'A', 6	)
insert into dealer(id , dealer_code, dealer_name, status, location_id) values (43  ,'70150', 'FREEWAY MAZDA'			, 'A', 6	)
