
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (1   ,'10102', 'UNIVERSITY MAZDA'			, 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (2   ,'10131', 'OAK TREE MAZDA'			, 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (3   ,'10707', 'TUSTIN MAZDA'				, 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (4   ,'34439', 'WANTAGH MAZDA'			    , 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (5   ,'34521', 'MAZDA OF NORTH MIAMI'		, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (6   ,'34541', 'MAZDA SOUTH'				, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (7   ,'50210', 'OCEAN MAZDA'				, 'A', 'GU', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (8   ,'51617', 'CULVER CITY MAZDA'		    , 'A', 'GU', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (9   ,'61566', 'GALPIN MAZDA'				, 'A', 'MW', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (10  ,'10803', 'CLASSIC MAZDA'			    , 'A', 'MW', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (11  ,'10823', 'CAPITOL MAZDA'			    , 'A', 'MW', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (12  ,'34575', 'CARDINALEWAY MAZDA VEGAS'	, 'A', 'MW', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (13  ,'61534', 'SPORT MAZDA'				, 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (14  ,'61593', 'MAZDA OF DELRAY BEACH'	    , 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (15  ,'61622', 'WAYNE MAZDA'				, 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (16  ,'61623', 'GUNTHER MAZDA'			    , 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (17  ,'61624', 'MAZDA OF LODI'			    , 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (18  ,'60135', 'CORY FAIRBANKS MAZDA'		, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (19  ,'61420', 'JEFF HAAS MAZDA'			, 'A', 'GU', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (20  ,'61429', 'BOB BAKER MAZDA'			, 'A', 'GU', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (21  ,'61449', 'MAZDA OF SOUTH CHARLOTTE'	, 'A', 'MW', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (22  ,'61540', 'MAZDA OF EVERETT'			, 'A', 'MW', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (23  ,'61590', 'QUIRK MAZDA'				, 'A', 'MW', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (24  ,'61610', 'WALSER BURNSVILLE MAZDA'	, 'A', 'MW', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (25  ,'61614', 'NORTH PARK MAZDA'			, 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (26  ,'61635', 'LUTHER BROOKDALE MAZDA'	, 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (27  ,'60181', 'DUBLIN MAZDA'				, 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (28  ,'61471', 'ROGER MAZDA GEORGETOWN'	, 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (29  ,'61611', 'HAMILTON MAZDA'			, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (30  ,'61613', 'NORTH PENN MAZDA'			, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (31  ,'61626', 'MORRIES MINNETONKA MAZDA'	, 'A', 'GU', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (32  ,'61629', 'MAZDA OF WEST CHESTER'	    , 'A', 'GU', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (33  ,'61637', 'PUTNAM MAZDA'				, 'A', 'MW', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (34  ,'60170', 'SMITH HAVEN MAZDA'		    , 'A', 'MW', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (35  ,'60172', 'RILEY MAZDA'				, 'A', 'MW', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (36  ,'60188', 'PALISADES MAZDA'			, 'A', 'MW', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (37  ,'61432', 'CLASSIC MAZDA'			    , 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (38  ,'61504', 'WERNER MAZDA'				, 'A', 'NE', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (39  ,'61542', 'MAZDA OF WEST RIDGE'		, 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (40  ,'61561', 'MORRIES INVER GROVE MAZDA' , 'A', 'NE', '02', '02')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (41  ,'61628', 'COLONIAL MAZDA'			, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (42  ,'34638', 'PUGI MAZDA'				, 'A', 'GU', '01', '01')
insert into dealer_details(id , dealer_code, dealer_name, status, region, zone, district) values (43  ,'70150', 'FREEWAY MAZDA'			    , 'A', 'GU', '02', '02')
